# Generated by Django 3.2.4 on 2021-06-09 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('image', models.TextField(max_length=500)),
                ('description', models.TextField(max_length=500)),
                ('date_create_at', models.DateTimeField(auto_now_add=True)),
                ('date_update_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create_at', models.DateTimeField(auto_now_add=True)),
                ('date_update_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.TextField(max_length=500)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('content', models.TextField(max_length=10000)),
                ('description', models.TextField(max_length=5000)),
                ('name', models.TextField(max_length=500)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.categorymodel')),
            ],
        ),
    ]
